/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Grant a user's global role — admin only */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    username: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        globalRole: string;
                    };
                };
            };
            responses: {
                /** @description The role was granted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            username: string;
                            /** @enum {string} */
                            globalRole: "user" | "setter" | "admin";
                        };
                    };
                };
                /** @description `globalRole` is not one of `user`, `setter`, `admin` (`admin_role_invalid`), or the caller tried to remove their own admin role (`admin_self_demotion`) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description Signed in, but not an admin (`admin_forbidden`), or authenticated by an access token rather than an interactive session (`session_required`) — this route is session-only, exactly like `/auth/tokens` */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description No such user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        username: string;
                        /** Format: email */
                        email: string;
                        password: string;
                        displayName: string;
                    };
                };
            };
            responses: {
                /** @description The account was created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            username: string;
                            email: string;
                            displayName: string;
                            /** @enum {string} */
                            globalRole: "user" | "setter" | "admin";
                            locale: string;
                            timezone: string;
                            totpEnabled: boolean;
                            /** Format: date-time */
                            createdAt: string;
                        };
                    };
                };
                /** @description That username or email is already registered (`username_taken` or `email_taken`) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description The request body failed validation */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in and receive a session cookie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        usernameOrEmail: string;
                        password: string;
                        totpCode?: string;
                    };
                };
            };
            responses: {
                /** @description Signed in */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                id: number;
                                username: string;
                                email: string;
                                displayName: string;
                                /** @enum {string} */
                                globalRole: "user" | "setter" | "admin";
                                locale: string;
                                timezone: string;
                                totpEnabled: boolean;
                                /** Format: date-time */
                                createdAt: string;
                            };
                        };
                    };
                };
                /** @description Invalid credentials or a TOTP code is required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the current session
         * @description Public and idempotent on purpose: a caller whose session has already expired still gets its cookie cleared, rather than a 401.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Signed out (or was already signed out) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            username: string;
                            email: string;
                            displayName: string;
                            /** @enum {string} */
                            globalRole: "user" | "setter" | "admin";
                            locale: string;
                            timezone: string;
                            totpEnabled: boolean;
                            /** Format: date-time */
                            createdAt: string;
                        };
                    };
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * This document
         * @description Generated from the registry on every request, so it cannot drift from what the API actually serves.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The OpenAPI 3.1 document */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Interactive API reference */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description An HTML page that renders this document with a vendored viewer script */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/scalar-standalone.js": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The viewer's vendored script
         * @description Not part of the API surface — served only so `GET /docs` has no CDN dependency.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The vendored Scalar API Reference standalone bundle */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/javascript": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every language POST /submissions accepts a languageKey for, active or not */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Every language, including inactive ones (flagged via isActive, not omitted) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: {
                                key: string;
                                name: string;
                                extension: string;
                                isActive: boolean;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Organizations visible to the caller */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of organizations */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: {
                                id: number;
                                slug: string;
                                name: string;
                                about: string | null;
                                /** @enum {string} */
                                visibility: "public" | "private";
                                /** @enum {string} */
                                joinPolicy: "open" | "request" | "invite";
                                /** Format: date-time */
                                createdAt: string;
                            }[];
                            nextCursor: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A single organization visible to the caller */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The organization */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            slug: string;
                            name: string;
                            about: string | null;
                            /** @enum {string} */
                            visibility: "public" | "private";
                            /** @enum {string} */
                            joinPolicy: "open" | "request" | "invite";
                            /** Format: date-time */
                            createdAt: string;
                        };
                    };
                };
                /** @description No such organization, or one the caller may not see — the two are indistinguishable */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a content-addressed problem package
         * @description The body is the raw tar+zstd archive bytes (see @duckoj/package-format). The `hash` query parameter is the hash the client claims for it; the server unpacks the archive, recomputes the hash from the file digests, and rejects the upload if it disagrees.
         */
        post: {
            parameters: {
                query: {
                    hash: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/octet-stream": string;
                };
            };
            responses: {
                /** @description The package was verified and stored */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            hash: string;
                        };
                    };
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description The archive exceeds the server-configured upload size limit */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description The archive could not be unpacked, the claimed hash does not match its contents, the manifest is invalid, or two paths collide once case-folded or Unicode-normalised */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metadata for a stored package */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    hash: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The package */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            hash: string;
                            sizeBytes: number;
                            fileCount: number;
                            /** Format: date-time */
                            createdAt: string;
                        };
                    };
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description No such package */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description The `hash` path parameter is not a valid package hash */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/problems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Problems visible to the caller */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of problems */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: {
                                id: number;
                                code: string;
                                name: string;
                                /** @enum {string} */
                                visibility: "private" | "org" | "public";
                                hasPublishedRevision: boolean;
                                timeMs: number | null;
                                memoryKb: number | null;
                            }[];
                            nextCursor: string | null;
                        };
                    };
                };
                /** @description The request failed validation */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a problem */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        code: string;
                        name: string;
                        statement: string;
                        /**
                         * @default private
                         * @enum {string}
                         */
                        visibility?: "private" | "org" | "public";
                        /** @default [] */
                        orgSlugs?: string[];
                    };
                };
            };
            responses: {
                /** @description The created problem */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            code: string;
                            name: string;
                            /** @enum {string} */
                            visibility: "private" | "org" | "public";
                            hasPublishedRevision: boolean;
                            timeMs: number | null;
                            memoryKb: number | null;
                            statement: string;
                            testCount: number | null;
                            totalPoints: number | null;
                            checkerKind: string | null;
                            /** Format: date-time */
                            createdAt: string;
                            members: {
                                username: string;
                                /** @enum {string} */
                                role: "author" | "curator" | "tester";
                            }[];
                            orgSlugs: string[];
                        };
                    };
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description Signed in, but not permitted to perform this action on this problem */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description That problem code is already taken */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description The request failed validation */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/problems/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A single problem visible to the caller */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The problem */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            code: string;
                            name: string;
                            /** @enum {string} */
                            visibility: "private" | "org" | "public";
                            hasPublishedRevision: boolean;
                            timeMs: number | null;
                            memoryKb: number | null;
                            statement: string;
                            testCount: number | null;
                            totalPoints: number | null;
                            checkerKind: string | null;
                            /** Format: date-time */
                            createdAt: string;
                            members: {
                                username: string;
                                /** @enum {string} */
                                role: "author" | "curator" | "tester";
                            }[];
                            orgSlugs: string[];
                        };
                    };
                };
                /** @description No such problem, or one the caller may not see — the two are indistinguishable */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a problem's name, statement, visibility, sharing or membership */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name?: string;
                        statement?: string;
                        /** @enum {string} */
                        visibility?: "private" | "org" | "public";
                        orgSlugs?: string[];
                        members?: {
                            username: string;
                            /** @enum {string} */
                            role: "author" | "curator" | "tester";
                        }[];
                    };
                };
            };
            responses: {
                /** @description The updated problem */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            code: string;
                            name: string;
                            /** @enum {string} */
                            visibility: "private" | "org" | "public";
                            hasPublishedRevision: boolean;
                            timeMs: number | null;
                            memoryKb: number | null;
                            statement: string;
                            testCount: number | null;
                            totalPoints: number | null;
                            checkerKind: string | null;
                            /** Format: date-time */
                            createdAt: string;
                            members: {
                                username: string;
                                /** @enum {string} */
                                role: "author" | "curator" | "tester";
                            }[];
                            orgSlugs: string[];
                        };
                    };
                };
                /** @description The patch carried `code` (immutable) or would leave the problem with no author */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description Signed in, but not permitted to perform this action on this problem */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description No such problem, or one the caller may not see — the two are indistinguishable */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description The request failed validation */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/problems/{code}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A problem's revision history — draft, published and archived alike */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Every revision, oldest first */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            version: number;
                            /** @enum {string} */
                            state: "draft" | "published" | "archived";
                            packageHash: string;
                            notes: string | null;
                            timeMs: number;
                            memoryKb: number;
                            testCount: number;
                            totalPoints: number;
                            checkerKind: string;
                            createdBy: number;
                            /** Format: date-time */
                            createdAt: string;
                        }[];
                    };
                };
                /** @description No such problem, or the caller is not a member (any role) or admin — unlike GET /problems/{code}, public or org visibility alone is not enough to see revision history */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** Attach an already-uploaded package as a new draft revision */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        packageHash: string;
                        notes?: string;
                    };
                };
            };
            responses: {
                /** @description The new draft revision was created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            version: number;
                        };
                    };
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description Signed in, but not permitted to perform this action on this problem */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description No such problem, or no such package */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description The package manifest is invalid, or its paths collide */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/problems/{code}/revisions/{version}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish a draft or archived revision, archiving whatever was previously published */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    code: string;
                    version: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The revision is now published */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            version: number;
                        };
                    };
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description Signed in, but not permitted to perform this action on this problem */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description No such problem, or no such revision version */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description The request failed validation */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Submissions visible to the caller, newest first
         * @description Keyset-paginated on `id`, descending. Produces exactly the set `GET /submissions/{id}` would answer 200 for, one id at a time — never more. `user=` naming someone else's username returns an empty page for a non-admin rather than a 403, which would itself confirm the username exists.
         */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                    problem?: string;
                    user?: string;
                    verdict?: "AC" | "WA" | "TLE" | "MLE" | "OLE" | "RTE" | "IR" | "CE" | "IE";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of submissions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: {
                                id: number;
                                problemCode: string;
                                username: string;
                                languageKey: string;
                                /** @enum {string} */
                                state: "queued" | "compiling" | "grading" | "done" | "errored";
                                /** @enum {string|null} */
                                verdict: "AC" | "WA" | "TLE" | "MLE" | "OLE" | "RTE" | "IR" | "CE" | "IE" | null;
                                points: number | null;
                                maxPoints: number | null;
                                /** Format: date-time */
                                createdAt: string;
                            }[];
                            nextCursor: string | null;
                        };
                    };
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description The query string failed validation, or `cursor` is not a valid page cursor */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** Submit a solution for grading */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        problemCode: string;
                        languageKey: string;
                        source: string;
                    };
                };
            };
            responses: {
                /** @description The submission was accepted and queued */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                        };
                    };
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description No such problem, or no such language */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description The request body failed validation */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A submission visible to the caller */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The submission */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            problemCode: string;
                            languageKey: string;
                            /** @enum {string} */
                            state: "queued" | "compiling" | "grading" | "done" | "errored";
                            /** @enum {string|null} */
                            verdict: "AC" | "WA" | "TLE" | "MLE" | "OLE" | "RTE" | "IR" | "CE" | "IE" | null;
                            points: number | null;
                            maxPoints: number | null;
                            timeMs: number | null;
                            memoryKb: number | null;
                            compileOutput: string | null;
                            cases: {
                                groupIndex: number;
                                caseIndex: number;
                                /** @enum {string|null} */
                                verdict: "AC" | "WA" | "TLE" | "MLE" | "OLE" | "RTE" | "IR" | "CE" | "IE" | null;
                                skipped: boolean;
                                timeMs: number;
                                memoryKb: number;
                                points: number;
                                maxPoints: number;
                                feedback: string | null;
                            }[];
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            judgedAt: string | null;
                        };
                    };
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description No such submission, or one the caller may not see — the two are indistinguishable */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description The `id` path parameter is not a valid submission id */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's personal access tokens */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The tokens, never including the secret itself */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            name: string;
                            scopes: string[];
                            /** Format: date-time */
                            lastUsedAt: string | null;
                            /** Format: date-time */
                            expiresAt: string | null;
                            /** Format: date-time */
                            createdAt: string;
                        }[];
                    };
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description Signed in, but authenticated by an access token rather than an interactive session (`session_required`) — credential management is session-only */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** Mint a personal access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name: string;
                        /** @default [] */
                        scopes?: ("problems:read" | "problems:write" | "problems:publish" | "submissions:read" | "submissions:write" | "orgs:read" | "packages:read" | "packages:write" | "languages:read")[];
                        /** Format: date-time */
                        expiresAt?: string;
                    };
                };
            };
            responses: {
                /** @description The token was minted; `token` is returned exactly once */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            token: string;
                        };
                    };
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description Signed in, but authenticated by an access token rather than an interactive session (`session_required`) — credential management is session-only */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description The request body failed validation */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a personal access token
         * @description Idempotent: revoking a token that does not exist, or belongs to someone else, still answers 204.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Revoked (or already gone) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description Signed in, but authenticated by an access token rather than an interactive session (`session_required`) — credential management is session-only */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/totp/begin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Begin TOTP enrolment
         * @description Upserts a fresh, unconfirmed secret. Calling this again before confirming silently replaces the previous secret — and calling it after 2FA is already enabled disables it until `confirm` succeeds.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The secret and its otpauth:// URL, to render as a QR code */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            secret: string;
                            otpauthUrl: string;
                        };
                    };
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description Signed in, but authenticated by an access token rather than an interactive session (`session_required`) — credential management is session-only */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/totp/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm TOTP enrolment */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        code: string;
                    };
                };
            };
            responses: {
                /** @description Enrolment confirmed; the account now requires a TOTP code at login */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description Signed in, but authenticated by an access token rather than an interactive session (`session_required`) — credential management is session-only */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description The code is not a valid 6-digit code for the pending secret (`invalid_totp_enrolment_code`) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/totp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disable TOTP */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Disabled (or was already off) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
                /** @description Signed in, but authenticated by an access token rather than an interactive session (`session_required`) — credential management is session-only */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
