/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in and receive a session cookie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        usernameOrEmail: string;
                        password: string;
                        totpCode?: string;
                    };
                };
            };
            responses: {
                /** @description Signed in */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                id: number;
                                username: string;
                                email: string;
                                displayName: string;
                                /** @enum {string} */
                                globalRole: "user" | "setter" | "admin";
                                locale: string;
                                timezone: string;
                                totpEnabled: boolean;
                                /** Format: date-time */
                                createdAt: string;
                            };
                        };
                    };
                };
                /** @description Invalid credentials or a TOTP code is required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            username: string;
                            email: string;
                            displayName: string;
                            /** @enum {string} */
                            globalRole: "user" | "setter" | "admin";
                            locale: string;
                            timezone: string;
                            totpEnabled: boolean;
                            /** Format: date-time */
                            createdAt: string;
                        };
                    };
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": {
                            /** @default about:blank */
                            type: string;
                            title: string;
                            status: number;
                            detail?: string;
                            instance?: string;
                            code: string;
                            fields?: {
                                [key: string]: string[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Organizations visible to the caller */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of organizations */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: {
                                id: number;
                                slug: string;
                                name: string;
                                about: string | null;
                                /** @enum {string} */
                                visibility: "public" | "private";
                                /** @enum {string} */
                                joinPolicy: "open" | "request" | "invite";
                                /** Format: date-time */
                                createdAt: string;
                            }[];
                            nextCursor: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a solution for grading */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        problemCode: string;
                        languageKey: string;
                        source: string;
                    };
                };
            };
            responses: {
                /** @description The submission was accepted and queued */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A submission visible to the caller */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | null;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The submission */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            problemCode: string;
                            languageKey: string;
                            /** @enum {string} */
                            state: "queued" | "compiling" | "grading" | "done" | "errored";
                            /** @enum {string|null} */
                            verdict: "AC" | "WA" | "TLE" | "MLE" | "OLE" | "RTE" | "IR" | "IE" | null;
                            points: number | null;
                            maxPoints: number | null;
                            timeMs: number | null;
                            memoryKb: number | null;
                            compileOutput: string | null;
                            cases: {
                                groupIndex: number;
                                caseIndex: number;
                                /** @enum {string|null} */
                                verdict: "AC" | "WA" | "TLE" | "MLE" | "OLE" | "RTE" | "IR" | "IE" | null;
                                skipped: boolean;
                                timeMs: number;
                                memoryKb: number;
                                points: number;
                                maxPoints: number;
                                feedback: string | null;
                            }[];
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            judgedAt: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
