export * as schema from './schema/index.js';
export { createDb, type Db } from './client.js';
/**
 * The diacritic fold (D185), exported by name as well as through `schema`
 * because it is the ONE definition of "the same name, however it was typed":
 * `users.search_fold` is generated by it and every search folds its needle
 * with it. A second copy anywhere is a search that silently stops matching.
 */
export { searchFold } from './schema/identity.js';
export { runMigrations } from './migrate.js';
export {
  hashJudgeToken,
  verifyJudgeCredential,
  admittedJudgeCredentials,
  type JudgeCredentialRef,
  isRevokedTokenHash,
  REVOKED_TOKEN_PREFIX,
  touchJudgeLastSeen,
  recordJudgeCapabilities,
} from './judge-auth.js';
export { reclaimExpiredLeases } from './grading.js';
export { loadDriverLanguageMap, type DriverLanguageMap } from './language-drivers.js';
// Re-exported, not defined here (D159). The arithmetic moved to its own
// zero-dependency package so `apps/web`'s authoring form can apply the SAME
// function to values a setter has typed and not yet saved; `apps/api` and
// `apps/judged` keep importing it from `@duckoj/db`, which is where D154 put
// it and where every call site already looks.
export * from '@duckoj/language-limits';
export {
  contestProblemIdsForSubmissions,
  isTerminalSubmissionState,
  noteContestSubmissionCreated,
  noteContestVerdict,
  recomputeContestProblemStats,
  recomputeContestStats,
  type SubmissionOutcome,
} from './contest-stats.js';
