import { z } from 'zod';
import { ProblemDetails, Timestamp } from './common.js';
import { registry } from './registry.js';

export const Username = z
  .string()
  .min(3)
  .max(32)
  .regex(/^[A-Za-z0-9_.-]+$/, 'may contain letters, digits, dot, underscore and hyphen only');

export const Password = z.string().min(10).max(256);

/**
 * A person's rendered name — one schema, used by registration and by the
 * profile edit alike.
 *
 * Two things it is not, both of which it was:
 *
 *  - **Not `min(1)` on the raw string.** `'   '` satisfies that, and three
 *    spaces are a name that renders as nothing at all: an empty heading on
 *    the profile, an empty cell in the user list, an empty author on every
 *    clarification. `.trim()` runs FIRST, so `min(1)` means what it looks
 *    like it means, and `max` measures the name rather than the padding.
 *  - **Not two different rules.** Registration capped at 64 and
 *    `UpdateMeRequest` at 100, so the same account could hold a name it
 *    could not have been created with. Unified at 100 — the wider of the
 *    two, so no stored name becomes unsavable.
 *
 * The trim is a transform, not a refusal: `'  Lan  '` is a typo, not an
 * attack, and correcting it is friendlier than a 422 about invisible
 * characters. It also means two accounts cannot wear the same name padded
 * differently.
 */
export const DisplayName = z.string().trim().min(1).max(100);

export const RegisterRequest = z.object({
  username: Username,
  email: z.string().email(),
  password: Password,
  displayName: DisplayName,
});
export type RegisterRequestDto = z.infer<typeof RegisterRequest>;

export const LoginRequest = z.object({
  usernameOrEmail: z.string().min(1),
  password: z.string().min(1),
  totpCode: z.string().regex(/^\d{6}$/).optional(),
  /**
   * A single-use TOTP recovery code (D39), the alternative to `totpCode` when
   * the authenticator is gone. Deliberately loose — the server canonicalizes
   * (uppercase, non-alphanumerics dropped) before hashing, so a code typed
   * without its dash, in lowercase, or with a stray space still works. A
   * strict shape here would answer 422 for a mistyped credential, which is a
   * different thing from "that code is wrong" and would escape D16's window.
   */
  recoveryCode: z.string().min(1).max(64).optional(),
});
export type LoginRequestDto = z.infer<typeof LoginRequest>;

export const MeResponse = z.object({
  id: z.number().int(),
  username: z.string(),
  email: z.string(),
  displayName: z.string(),
  globalRole: z.enum(['user', 'setter', 'admin']),
  /**
   * The reader's own preferences, or `null` where they have never chosen
   * one (D57). `null` is not "vi" and not the server's zone: it means the
   * client keeps doing what it did before anybody had a setting — resolve
   * the locale from `navigator.language` (D18) and render times in the
   * browser's own zone. A non-null value beats both.
   */
  locale: z.string().nullable(),
  timezone: z.string().nullable(),
  totpEnabled: z.boolean(),
  /**
   * How many unused TOTP recovery codes the account still holds (D39). Zero
   * whenever 2FA is off, so the security page can tell "none left, regenerate
   * now" apart from "nothing to have".
   */
  recoveryCodesRemaining: z.number().int(),
  /** Nothing is gated on this yet — see 3f §5. */
  emailVerified: z.boolean(),
  /**
   * This account holds a password it never chose (D61) and must replace it
   * before doing anything else.
   *
   * Set on every account minted by a school's roster import: the password was
   * generated by the server and handed to a teacher on a printed sheet, so
   * until the pupil changes it, one piece of paper is the credential for a
   * whole class. Carried on `MeResponse` rather than only on the login
   * response, because a session survives a page reload and the client has to
   * be able to re-derive the obligation from `GET /auth/me` alone.
   *
   * `POST /auth/password/change` is the one route that clears it, and is also
   * the one route that accepts a new password WITHOUT the old one while it is
   * set. D61 left every OTHER route to the web client; D102 narrows that to
   * the session: while this flag is set, `POST /auth/tokens` is `409
   * password_change_required` and so is any request authenticated by a token
   * that was minted before it. A non-browser client (`oj`, the MCP server)
   * therefore learns the obligation from this field at login and from that
   * refusal afterwards, rather than silently working around a gate that only
   * the browser applies.
   */
  mustChangePassword: z.boolean(),
  createdAt: Timestamp,
});
export type MeResponseDto = z.infer<typeof MeResponse>;

export const LoginResponse = z.object({ user: MeResponse });

/**
 * Whether this deployment takes sign-ups (D200).
 *
 * A rung name rather than a boolean, and deliberately so: `REGISTRATION`
 * grows a third value the day an invitation mechanism exists, and a client
 * that switched on `open: true/false` would have to be changed to notice.
 * Every client that only wants "is there a form" asks `=== 'open'`.
 */
export const RegistrationStateResponse = z.object({
  registration: z.enum(['open', 'closed']),
});
export type RegistrationStateResponseDto = z.infer<typeof RegistrationStateResponse>;

registry.registerPath({
  method: 'get',
  path: '/auth/registration',
  tags: ['Auth'],
  summary: 'Whether this deployment takes sign-ups',
  description:
    'Public, and it has to be: the reader is a visitor with no account (D200). It carries the rung and ' +
    'nothing else — no account count, no roster, no address — so a register screen can say "this site ' +
    'does not take sign-ups" instead of 403-ing a form after five fields (D145). `closed` is the ' +
    'default: a school district\u2019s pupils arrive by D61\u2019s roster import, not by signing up.',
  responses: {
    200: {
      description: 'The registration rung in effect for this deployment',
      content: { 'application/json': { schema: RegistrationStateResponse } },
    },
  },
});

registry.registerPath({
  method: 'post',
  path: '/auth/register',
  tags: ['Auth'],
  summary: 'Create an account',
  description:
    'Refused 403 `registration_closed` unless this deployment is on the `open` rung or the caller is a ' +
    'global admin (D200) — ask `GET /auth/registration` first. The default rung is `closed`.\n\n' +
    'On the `open` rung a taken EMAIL is answered with 201 and a body of the same shape, and no account ' +
    'is created (D26) — an address is not public, and a distinguishable refusal made this endpoint an ' +
    'email-enumeration oracle. A taken USERNAME is still a 409: a username is public, and refusing it ' +
    'is the only way a caller can pick another one. A GLOBAL ADMIN is told the truth about both — a ' +
    '409 `email_taken` (D200, on D61\u2019s argument): they are session-authenticated and authorized, ' +
    'so they are not the anonymous caller D26 closed the oracle against, and a phantom account they ' +
    'cannot find out about is the worse outcome.',
  request: { body: { content: { 'application/json': { schema: RegisterRequest } } } },
  responses: {
    201: {
      description:
        'The account was created — OR the address was already registered, in which case nothing was ' +
        'created and this response is deliberately indistinguishable from the one above (D26)',
      content: { 'application/json': { schema: MeResponse } },
    },
    403: {
      description:
        'This deployment does not take sign-ups (`registration_closed`) — D200. The refusal is a ' +
        'function of the rung and of who is asking, and of NOTHING about the request body: every ' +
        'anonymous caller gets it for every address, including addresses that have never existed, and ' +
        'gets it before the address is looked at. That is what closes D26\u2019s residual oracle on ' +
        'this rung rather than merely narrowing it.',
      content: { 'application/problem+json': { schema: ProblemDetails } },
    },
    409: {
      description:
        'That username is already registered (`username_taken`) — or, for a global admin only, that ' +
        'email is (`email_taken`, D200)',
      content: { 'application/problem+json': { schema: ProblemDetails } },
    },
    422: {
      description: 'The request body failed validation',
      content: { 'application/problem+json': { schema: ProblemDetails } },
    },
    429: {
      description:
        'Too many registrations from this client IP (`register_rate_limited`) — thirty per hour (D26). ' +
        'Unlike login, EVERY attempt counts: what is metered is the cost of an argon2id hash, which a ' +
        'successful registration pays in full. The refusal itself records nothing, so the window drains. ' +
        '`Retry-After` carries the whole seconds until another attempt will be accepted.',
      headers: {
        'Retry-After': {
          description: 'Whole seconds until another attempt will be accepted',
          required: true,
          schema: { type: 'integer' },
        },
      },
      content: { 'application/problem+json': { schema: ProblemDetails } },
    },
  },
});

/**
 * `currentPassword` is optional for exactly one reason: an account flagged
 * `mustChangePassword` (D61) does not have a password of its own to prove —
 * the one it holds was printed on a sheet handed round a classroom, and
 * demanding it back would make the school's own printout the credential that
 * unlocks the change. What stands in for it is the route's `@SessionOnly`
 * marker: the caller is holding an interactive session cookie for this
 * account, which a personal access token cannot supply.
 *
 * For every other account it is REQUIRED, and its absence is a 422 rather
 * than a silent success — an unattended browser must not be one POST away
 * from a permanent account takeover.
 */
export const ChangePasswordRequest = z
  .object({
    currentPassword: z.string().min(1).max(256).optional(),
    newPassword: Password,
  })
  .strict();
export type ChangePasswordRequestDto = z.infer<typeof ChangePasswordRequest>;

registry.registerPath({
  method: 'post',
  path: '/auth/login',
  tags: ['Auth'],
  summary: 'Sign in and receive a session cookie',
  description:
    'When the account has 2FA on, exactly one of `totpCode` or `recoveryCode` must accompany the '+
    'password; `totpCode` wins if both are sent. A recovery code is spent on the sign-in it '+
    'succeeds at, and when it was the last one the account is sent a notification telling its '+
    'holder to generate a new set (D39).',
  request: { body: { content: { 'application/json': { schema: LoginRequest } } } },
  responses: {
    200: { description: 'Signed in', content: { 'application/json': { schema: LoginResponse } } },
    401: {
      description:
        'Invalid credentials, or a second factor is required (`totp_required`), or the second factor ' +
        'was wrong (`invalid_totp_code`). A `recoveryCode` that is unknown, malformed or ALREADY SPENT ' +
        'answers `invalid_totp_code` too (D39): a caller must not be able to tell a code that never ' +
        'existed from one that has already been used.',
      content: { 'application/problem+json': { schema: ProblemDetails } },
    },
    429: {
      description:
        'Too many FAILED sign-in attempts (`login_rate_limited`) — ten per identifier and thirty ' +
        'per client IP, each per fifteen minutes (D16). A successful sign-in consumes neither ' +
        'window, and the refusal itself records nothing. `Retry-After` carries the whole seconds ' +
        'until the window frees up.',
      headers: {
        'Retry-After': {
          description: 'Whole seconds until another attempt will be accepted',
          required: true,
          schema: { type: 'integer' },
        },
      },
      content: { 'application/problem+json': { schema: ProblemDetails } },
    },
  },
});

registry.registerPath({
  method: 'post',
  path: '/auth/logout',
  tags: ['Auth'],
  summary: 'End the current session',
  description:
    'Public and idempotent on purpose: a caller whose session has already expired still gets its cookie ' +
    'cleared, rather than a 401.',
  responses: {
    204: { description: 'Signed out (or was already signed out)' },
  },
});

registry.registerPath({
  method: 'post',
  path: '/auth/password/change',
  tags: ['Auth'],
  summary: 'Change your own password',
  description:
    'Session-only: an access token cannot rewrite the credential that governs it. `currentPassword` ' +
    'is required EXCEPT while the account carries `mustChangePassword` (D61), where the password on ' +
    'record was generated by a roster import and printed on a sheet rather than chosen. Succeeding ' +
    'clears that flag and ends every other session and access token the account holds, exactly as a ' +
    'password reset does.',
  request: { body: { content: { 'application/json': { schema: ChangePasswordRequest } } } },
  responses: {
    204: { description: 'The password was changed' },
    401: {
      description: 'Not signed in, or `currentPassword` is wrong (`invalid_credentials`)',
      content: { 'application/problem+json': { schema: ProblemDetails } },
    },
    403: {
      description: 'Authenticated by an access token rather than a session (`session_required`)',
      content: { 'application/problem+json': { schema: ProblemDetails } },
    },
    422: {
      description:
        'The body failed validation, or `currentPassword` was omitted by an account that is not ' +
        'flagged `mustChangePassword` (`current_password_required`)',
      content: { 'application/problem+json': { schema: ProblemDetails } },
    },
    429: {
      description:
        'Ten password attempts have been made for this account in the last fifteen minutes ' +
        '(`password_check_rate_limited`, D73). ONE budget is shared with `DELETE /auth/totp`, ' +
        'keyed on the account, and it is read BEFORE the password is verified. An account ' +
        'flagged `mustChangePassword` never spends it: that path checks no password.',
      headers: {
        'Retry-After': {
          description: 'Whole seconds until another attempt will be accepted',
          schema: { type: 'string' },
        },
      },
      content: { 'application/problem+json': { schema: ProblemDetails } },
    },
  },
});

registry.registerPath({
  method: 'get',
  path: '/auth/me',
  tags: ['Auth'],
  summary: 'The signed-in user',
  responses: {
    200: { description: 'Profile', content: { 'application/json': { schema: MeResponse } } },
    401: {
      description: 'Not signed in',
      content: { 'application/problem+json': { schema: ProblemDetails } },
    },
  },
});

/**
 * Password reset and address verification.
 *
 * `forgot` answers the same way for every syntactically valid address, so the
 * endpoint cannot be used to ask whether someone has an account here.
 */
export const ForgotPasswordRequest = z.object({ email: z.string().email() }).strict();
export type ForgotPasswordRequestDto = z.infer<typeof ForgotPasswordRequest>;

export const ResetPasswordRequest = z
  .object({ token: z.string().min(1).max(256), password: z.string().min(12).max(256) })
  .strict();
export type ResetPasswordRequestDto = z.infer<typeof ResetPasswordRequest>;

export const VerifyEmailRequest = z.object({ token: z.string().min(1).max(256) }).strict();
export type VerifyEmailRequestDto = z.infer<typeof VerifyEmailRequest>;

const INVALID_TOKEN = {
  description: 'The link is invalid, expired, or already used — all answered identically',
  content: { 'application/problem+json': { schema: ProblemDetails } },
};

registry.registerPath({
  method: 'post',
  path: '/auth/password/forgot',
  tags: ['Auth'],
  summary: 'Send a password-reset link',
  request: { body: { content: { 'application/json': { schema: ForgotPasswordRequest } } } },
  responses: {
    202: { description: 'Accepted — answered identically whether or not the account exists' },
    422: {
      description: 'Not a syntactically valid address',
      content: { 'application/problem+json': { schema: ProblemDetails } },
    },
    503: {
      description:
        'D155 — this production deployment has no SMTP transport, so no mail can be sent to anyone ' +
        '(`mail_unavailable`). Decided by the server\'s own configuration and never by the address in the ' +
        'request, so the 202/503 split says nothing about whether an account exists: every caller gets the ' +
        'same answer for every address. Answered before the lookup, so the timing does not leak either.',
      content: { 'application/problem+json': { schema: ProblemDetails } },
    },
  },
});

registry.registerPath({
  method: 'post',
  path: '/auth/password/reset',
  tags: ['Auth'],
  summary: 'Redeem a reset link; ends every session for that user',
  request: { body: { content: { 'application/json': { schema: ResetPasswordRequest } } } },
  responses: { 200: { description: 'Password changed' }, 400: INVALID_TOKEN },
});

registry.registerPath({
  method: 'post',
  path: '/auth/email/verify/send',
  tags: ['Auth'],
  summary: 'Send an address-confirmation link to the signed-in user',
  responses: {
    202: { description: 'Accepted' },
    401: { description: 'Not signed in' },
    503: {
      description: 'D155 — no SMTP transport on this production deployment (`mail_unavailable`)',
      content: { 'application/problem+json': { schema: ProblemDetails } },
    },
  },
});

registry.registerPath({
  method: 'post',
  path: '/auth/email/verify',
  tags: ['Auth'],
  summary: 'Confirm an email address',
  request: { body: { content: { 'application/json': { schema: VerifyEmailRequest } } } },
  responses: { 200: { description: 'Address confirmed' }, 400: INVALID_TOKEN },
});
