ALTER TABLE "contest_participations" DROP CONSTRAINT "contest_participations_contest_id_contests_id_fk";
--> statement-breakpoint
ALTER TABLE "contest_participations" ADD CONSTRAINT "contest_participations_contest_id_contests_id_fk" FOREIGN KEY ("contest_id") REFERENCES "public"."contests"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "problem_revisions_problem_identity_idx" ON "problem_revisions" USING btree ("problem_id","id");--> statement-breakpoint
-- Hand-written, and it is the point of this migration (B-31).
--
-- `problems.current_revision_id` was the ONE id column in this schema
-- carrying no foreign key at all, and it is the column that decides which
-- package grades a submission: `SubmissionAccessService.create` loads the
-- revision by this id alone and never re-checks whose problem it belongs to.
-- So the key is COMPOSITE — it states "the current revision is a revision OF
-- THIS PROBLEM", which is the fact that matters; a one-column key would only
-- have said "some revision exists".
--
-- Not generated by drizzle-kit because it cannot be: the table config for
-- `problems` runs while `problems` is being defined and `problem_revisions`
-- is declared below it, so naming those columns in `foreignKey()` is a
-- temporal-dead-zone error. drizzle-kit diffs the SNAPSHOT against the schema
-- file, so a constraint in neither is invisible to it and will not be dropped
-- by a later `generate`. `packages/db/test/referential-integrity.spec.ts`
-- asserts it against a real migrated database, which is where it is pinned.
--
-- MATCH SIMPLE (the default) leaves a NULL `current_revision_id` — a problem
-- with no published revision — unconstrained, which is the intended state.
-- NO ACTION rather than RESTRICT so the check falls to the end of the
-- statement: deleting a problem cascades its revisions away and removes the
-- referencing row in the same statement, and RESTRICT's immediate check would
-- refuse that. Verified on a throwaway database.
--
-- No backfill and no dedupe: checked read-only against the live province
-- database first — 0 problems with a dangling `current_revision_id`, 0
-- pointing at another problem's revision, 0 out of step with
-- `problem_revisions.state`.
ALTER TABLE "problems" ADD CONSTRAINT "problems_current_revision_fk" FOREIGN KEY ("id","current_revision_id") REFERENCES "public"."problem_revisions"("problem_id","id") ON DELETE no action ON UPDATE no action;
