import { sql, type SQL, type SQLWrapper } from 'drizzle-orm';
import {
  bigserial,
  bigint,
  boolean,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from 'drizzle-orm/pg-core';

export const userStatus = pgEnum('user_status', ['active', 'suspended', 'pending']);
export const globalRole = pgEnum('global_role', ['user', 'setter', 'admin']);

/**
 * What a one-time token is for.
 *
 * One table with a purpose column rather than two tables: expiry, hashing and
 * single-use redemption are identical for both, and duplicating them three
 * lines at a time is how they drift. The cost is that every redemption **must**
 * filter on `purpose` as well as on the hash — a verification link that can set
 * a password is exactly the bug this shape makes possible, and it has its own
 * test for that reason.
 */
export const oneTimeTokenPurpose = pgEnum('one_time_token_purpose', [
  'password_reset',
  'email_verification',
]);

/**
 * The one definition of "the same name, however it was typed" (D185).
 *
 * A Vietnamese reader types `nguyen` and means `Nguyễn`. Nothing in this
 * codebase may hold a second copy of that rule: the stored column below and
 * the needle every search builds are folded by THIS function, so a query
 * string and the row it is meant to find can never be folded differently.
 *
 * Four steps, in this order:
 *
 *  1. `lower()` — case folding first, so `Đ` reaches the `đ` in step 4.
 *  2. `normalize(…, NFD)` — every precomposed Vietnamese letter becomes its
 *     base plus combining marks. Vietnamese needs TWO marks on one vowel
 *     (`ế` is `e` + circumflex + acute, `ữ` is `u` + horn + tilde), and NFD
 *     peels both.
 *  3. strip `U+0300–U+036F` — the combining diacritical marks block, which is
 *     where every mark step 2 produced lives, the horn (`U+031B`) and the
 *     breve (`U+0306`) included.
 *  4. `translate` — `đ` has NO decomposition (it is a letter with a stroke,
 *     not a letter with a mark), so it is mapped by hand; `-`, `_` and `.`
 *     become spaces so that a word inside a username is a word (`hs-nguyen`
 *     is found by `nguyen`, which is the same promise made to a display
 *     name).
 *
 * **`unaccent` was refused, and the reason is not taste.** It is an extension
 * this database does not have (`pg_extension` holds `plpgsql` and nothing
 * else) and — decisively — `unaccent(text)` is **STABLE**, not `IMMUTABLE`,
 * because its dictionary is a file on disk. A STABLE expression may not be
 * stored in a generated column and may not be indexed. `normalize()` is
 * `IMMUTABLE` and needs no extension, so it can be, and is.
 *
 * The character-class literal is written with `\uXXXX` escapes rather than the
 * marks themselves: a combining mark in source is invisible, and a reviewer
 * cannot tell a correct range from a mangled one by looking at it.
 */
export function searchFold(expression: SQL | SQLWrapper): SQL<string> {
  return sql`translate(regexp_replace(normalize(lower(${expression}), NFD), '[\\u0300-\\u036f]', '', 'g'), 'đ-_.', 'd   ')`;
}

export const users = pgTable(
  'users',
  {
    id: bigserial('id', { mode: 'number' }).primaryKey(),
    username: text('username').notNull(),
    email: text('email').notNull(),
    passwordHash: text('password_hash').notNull(),
    status: userStatus('status').notNull().default('active'),
    globalRole: globalRole('global_role').notNull().default('user'),
    displayName: text('display_name').notNull(),
    about: text('about'),
    avatarKey: text('avatar_key'),
    country: text('country'),
    /**
     * The reader's own IANA zone and BCP-47 tag — **nullable, and `NULL` is
     * the point** (D57).
     *
     * Both were `NOT NULL DEFAULT` ('Asia/Ho_Chi_Minh', 'vi') until 0023, and
     * with a default there is no such thing as "the reader has not chosen":
     * a server value that beats the browser's own would have forced ICT
     * clocks and Vietnamese onto every account that never opened the settings
     * screen, which is exactly what D18's `navigator.language` resolution
     * exists to avoid. `NULL` means "not chosen — use the client's own", so
     * the stored value only ever overrides a default when somebody set it.
     */
    timezone: text('timezone'),
    locale: text('locale'),
    /** When this address was confirmed. Nothing is gated on it yet (3f §5). */
    emailVerifiedAt: timestamp('email_verified_at', { withTimezone: true }),
    /**
     * The account holds a password it never chose (D61).
     *
     * Set on every account minted by a bulk roster import, where the
     * password was generated by the server and handed to a teacher on a
     * printout — so between the import and the pupil's first sign-in, one
     * sheet of paper is the credential for every account on it. The flag is
     * what lets `POST /auth/password/change` accept a new password WITHOUT
     * the old one (the session cookie is the proof of possession) and what
     * lets the web force that screen before anything else.
     *
     * `NOT NULL DEFAULT false`, unlike `locale`/`timezone` (D57): there is
     * no third state here. Every account that existed before 0024 chose its
     * own password, and `false` says exactly that.
     */
    mustChangePassword: boolean('must_change_password').notNull().default(false),
    /**
     * `username` and `display_name`, folded by `searchFold` above, in one
     * string a `LIKE` can walk (D185, migration 0047).
     *
     * **Stored, not computed per row.** Measured on a 25 000-account province
     * copy, the worst case a search has — a query matching nothing, which is
     * every typo — cost **172 ms** with the fold applied per row and **4.2 ms**
     * against this column. The roster search inside one 5 000-pupil school
     * went from 22–40 ms to 5.5 ms. That factor is the whole justification for
     * the column; nothing else in this table is denormalised.
     *
     * The two fields share one string BY DESIGN: it is what lets a teacher
     * type either the account name or the person's name into one box and get
     * an answer, and the separator between them is a space, so the
     * word-prefix seek below cannot match ACROSS the join.
     */
    searchFold: text('search_fold').generatedAlwaysAs(
      (): SQL => searchFold(sql`${users.username} || ' ' || ${users.displayName}`),
    ),
    rating: integer('rating'),
    maxRating: integer('max_rating'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('users_username_lower_idx').on(sql`lower(${t.username})`),
    uniqueIndex('users_email_lower_idx').on(sql`lower(${t.email})`),
  ],
);

export const sessions = pgTable(
  'sessions',
  {
    id: bigserial('id', { mode: 'number' }).primaryKey(),
    userId: bigint('user_id', { mode: 'number' })
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    tokenHash: text('token_hash').notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    ip: text('ip'),
    userAgent: text('user_agent'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('sessions_token_hash_idx').on(t.tokenHash),
    // For `ExpiredRowsSweeper`, not for `resolve` — every read is by
    // `token_hash` above. The sweep's `expires_at < now()` had no index at
    // all, so the hourly janitor sequentially scanned every session ever
    // created to find the expired ones (migration 0029).
    index('sessions_expires_at_idx').on(t.expiresAt),
  ],
);

export const accessTokens = pgTable(
  'access_tokens',
  {
    id: bigserial('id', { mode: 'number' }).primaryKey(),
    userId: bigint('user_id', { mode: 'number' })
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    tokenHash: text('token_hash').notNull(),
    scopes: text('scopes').array().notNull().default(sql`'{}'::text[]`),
    lastUsedAt: timestamp('last_used_at', { withTimezone: true }),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('access_tokens_token_hash_idx').on(t.tokenHash)],
);

export const totpCredentials = pgTable('totp_credentials', {
  userId: bigint('user_id', { mode: 'number' })
    .primaryKey()
    .references(() => users.id, { onDelete: 'cascade' }),
  secretEnc: text('secret_enc').notNull(),
  confirmedAt: timestamp('confirmed_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

/**
 * TOTP recovery codes (D39) — the way back in when the authenticator is gone.
 *
 * **Only the hash is stored**, exactly as `one_time_tokens` does and for the
 * same reason: a database leak must not hand over eight working second
 * factors. `sha256` rather than argon2 because the stored value is 50 bits of
 * SERVER-generated randomness, not a user-chosen password — there is no
 * dictionary to slow down, and a per-login argon2 verify against up to eight
 * rows at 19 MiB each would be a denial-of-service surface on a route anyone
 * can reach.
 *
 * `used_at` rather than a delete, so the count of what remains and the fact
 * that one was spent survive; the consume is a single
 * `UPDATE … WHERE used_at IS NULL RETURNING`, which is race-free on the row
 * itself and needs no advisory lock (unlike D34's `consumeOnce`, which has no
 * row to claim).
 */
export const totpRecoveryCodes = pgTable(
  'totp_recovery_codes',
  {
    id: bigserial('id', { mode: 'number' }).primaryKey(),
    userId: bigint('user_id', { mode: 'number' })
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    /** `sha256(canonical code)`, hex. Never the code itself. */
    codeHash: text('code_hash').notNull(),
    /** Set the moment the code is spent, in the statement that spends it. */
    usedAt: timestamp('used_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('totp_recovery_codes_user_hash_idx').on(t.userId, t.codeHash)],
);

/**
 * Password-reset and address-verification tokens.
 *
 * **Only the hash is stored.** A database leak must not hand over working reset
 * links, and nothing legitimately needs the plaintext once it has been sent.
 */
export const oneTimeTokens = pgTable(
  'one_time_tokens',
  {
    id: bigserial('id', { mode: 'number' }).primaryKey(),
    userId: bigint('user_id', { mode: 'number' })
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    purpose: oneTimeTokenPurpose('purpose').notNull(),
    /** `sha256(token)`, hex. Never the token itself. */
    tokenHash: text('token_hash').notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    /** Set on redemption, in the same transaction as the effect. */
    usedAt: timestamp('used_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('one_time_tokens_hash_idx').on(t.tokenHash),
    /** The sweep's predicate (migration 0029); `redeem` reads by hash. */
    index('one_time_tokens_expires_at_idx').on(t.expiresAt),
  ],
);

/**
 * One row per rate-limited attempt (D13). A fixed window is counted with
 * `SELECT count(*) WHERE created_at > now - window`, so the limiter needs no
 * counter to reset and no state beyond the rows themselves; `RateLimiter`
 * deletes a key's expired rows opportunistically on each check, which keeps
 * the table bounded without a cron.
 *
 * `purpose` is plain text, not the token enum: the limiter is generic and a
 * new limited action must not require a migration (the `contests.format`
 * reasoning).
 */
export const rateEvents = pgTable(
  'rate_events',
  {
    id: bigserial('id', { mode: 'number' }).primaryKey(),
    purpose: text('purpose').notNull(),
    /** What the limit is counted against — a lowercased email, an IP, an id. */
    key: text('key').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('rate_events_lookup_idx').on(t.purpose, t.key, t.createdAt),
    // `created_at` is the TRAILING column of the lookup index, and a btree
    // can only bound a scan by a PREFIX of its columns — so the sweeper's
    // `created_at < cutoff`, which names no purpose and no key, could never
    // use it and sequentially scanned the whole table (migration 0029).
    index('rate_events_created_at_idx').on(t.createdAt),
  ],
);

/**
 * In-app notifications (D14). Strictly per-user rows: the only visibility
 * rule is `user_id = actor`, enforced in `NotificationsService`, so the
 * table stays in the plain schema rather than the guarded one.
 *
 * `kind` is plain text with `payload` jsonb beside it — a new kind is a
 * producer and a renderer, never a migration. The payload is a snapshot
 * (usernames, slugs as they were), not foreign keys: a notification about
 * an org that was later renamed should still read the way it did when it
 * happened.
 */
export const notifications = pgTable(
  'notifications',
  {
    id: bigserial('id', { mode: 'number' }).primaryKey(),
    userId: bigint('user_id', { mode: 'number' })
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    kind: text('kind').notNull(),
    payload: jsonb('payload').notNull().default({}),
    readAt: timestamp('read_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('notifications_user_idx').on(t.userId, t.id)],
);
