import { existsSync } from 'node:fs';
import { mkdtemp, stat } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import { promisify } from 'node:util';
import { eq } from 'drizzle-orm';
import { afterAll, describe, expect, it } from 'vitest';
import { PostgreSqlContainer, type StartedPostgreSqlContainer } from '@testcontainers/postgresql';
import { createDb, hashJudgeToken, runMigrations, schema } from '../src/index.js';
import { problemMembers, problemRevisions, problems } from '../src/schema/guarded.js';

const execFileAsync = promisify(execFile);

// Same podman shim as harness.ts (see its comment) — this file starts its
// own container rather than sharing that one, because it needs the seed
// script's real, committed writes (a subprocess, over its own connection),
// not a transaction `withTestDb` would roll back.
if (!process.env.DOCKER_HOST) {
  const podmanSocket = `/run/user/${process.getuid?.() ?? 1000}/podman/podman.sock`;
  if (!existsSync('/var/run/docker.sock') && existsSync(podmanSocket)) {
    process.env.DOCKER_HOST = `unix://${podmanSocket}`;
  }
}

const REPO_ROOT = fileURLToPath(new URL('../../..', import.meta.url));
const SEED_SCRIPT = join(REPO_ROOT, 'scripts', 'seed-problem.ts');
const TSX_BIN = join(REPO_ROOT, 'packages', 'db', 'node_modules', '.bin', 'tsx');
// Recomputed after Task 13 deleted `problems/aplusb/init.yml` (now
// generated by judge-agent at materialisation time, not checked in) —
// `packDirectory` hashes every file under the directory, so removing one
// changes the package's content-addressed hash.
const REAL_APLUSB_HASH = '73d40a7e62d7019346f137048ee1f251e07cad9e4e34b8593f28a2f42f12e406';
const JUDGE_TOKEN = 'test-judge-token';

let container: StartedPostgreSqlContainer | undefined;

// Same retry as harness.ts's `stopWithRetry` (see its comment): rootless
// Podman occasionally fails to remove a container's network namespace when
// several are torn down within the same second, which this file — a fifth
// container alongside harness.ts's shared one — makes more likely, not
// less. A throwing `afterAll` would red this whole spec file over a stopped
// container the next sweep can still reap; retry, then warn and move on.
const STOP_RETRY_DELAYS_MS = [500, 1000, 2000];

async function stopWithRetry(target: { stop(): Promise<unknown> }): Promise<void> {
  for (let attempt = 0; ; attempt++) {
    try {
      await target.stop();
      return;
    } catch (error) {
      if (attempt >= STOP_RETRY_DELAYS_MS.length) {
        console.warn('[packages/db seed-script.spec] failed to stop Testcontainers container after retries:', error);
        return;
      }
      await new Promise((resolve) => setTimeout(resolve, STOP_RETRY_DELAYS_MS[attempt]));
    }
  }
}

afterAll(async () => {
  if (!container) return;
  await stopWithRetry(container);
}, 30_000);

async function runSeed(url: string, packageStoreDir: string): Promise<void> {
  await execFileAsync(TSX_BIN, [SEED_SCRIPT], {
    cwd: REPO_ROOT,
    env: { ...process.env, DATABASE_URL: url, JUDGE_TOKEN, PACKAGE_STORE_DIR: packageStoreDir },
  });
}

describe('seed-problem.ts', () => {
  it(
    // Controller addendum B1's required test: seeding twice leaves one
    // `judge_nodes` row, and the stored hash matches `hashJudgeToken(token)`.
    // Also proves the ordering this whole task exists for, the other way
    // around from the manual verification in the report: migrating fully
    // (through 0004, the FK migration) *before* seeding at all, mirroring
    // every future bring-up (migrate runs first, seed second) — the seed's
    // own inserts must not trip the constraint it motivated.
    'seeds a real package, repoints the revision, and registers one judge_nodes row across two runs against an already-migrated database',
    async () => {
      container = await new PostgreSqlContainer('postgres:16-alpine').start();
      const url = container.getConnectionUri();
      await runMigrations(url);

      // A scratch directory standing in for the named volume `api` and the
      // seed one-off container share in Compose — proves the seed writes
      // the archive to `PACKAGE_STORE_DIR`, in `FilesystemPackageStore`'s
      // own `<root>/<hash[0:2]>/<hash>` shard layout (Task 13), not just
      // the database rows the assertions below already covered.
      const packageStoreDir = await mkdtemp(join(tmpdir(), 'seed-script-store-'));

      await runSeed(url, packageStoreDir);
      await runSeed(url, packageStoreDir);

      const { db, close } = createDb(url);
      try {
        const judgeRows = await db.select().from(schema.judgeNodes);
        expect(judgeRows).toHaveLength(1);
        expect(judgeRows[0]!.name).toBe('judge-1');
        expect(judgeRows[0]!.tokenHash).toBe(hashJudgeToken(JUDGE_TOKEN));

        const [problem] = await db.select().from(problems);
        const revisionRows = await db.select().from(problemRevisions);
        expect(revisionRows).toHaveLength(1);
        expect(revisionRows[0]!.packageHash).toBe(REAL_APLUSB_HASH);
        expect(revisionRows[0]!.id).toBe(problem!.currentRevisionId);

        // R7: the seed script's locked service account exists and is
        // reachable with no valid password — `'!'` is not a valid argon2
        // encoding, so `PasswordService.verify` fails closed on it.
        const [systemUser] = await db.select().from(schema.users).where(eq(schema.users.username, 'system'));
        expect(systemUser).toBeDefined();
        expect(systemUser!.passwordHash).toBe('!');

        // R7: the system account also holds the problem's `author`
        // membership, recorded the other way `problem_members` expects it.
        const authorRows = await db
          .select()
          .from(problemMembers)
          .where(eq(problemMembers.problemId, problem!.id));
        expect(authorRows).toEqual([{ problemId: problem!.id, userId: systemUser!.id, role: 'author' }]);

        // R9: the five revision metadata columns come from
        // `problems/aplusb/manifest.json`, not a hardcoded sentinel —
        // `{ limits: { timeMs: 1000, memoryKb: 65536 }, tests: [3 cases,
        // 1 point each], checker: { kind: 'standard' } }`.
        expect(revisionRows[0]!.timeMs).toBe(1000);
        expect(revisionRows[0]!.memoryKb).toBe(65536);
        expect(revisionRows[0]!.testCount).toBe(3);
        expect(revisionRows[0]!.totalPoints).toBe(3);
        expect(revisionRows[0]!.checkerKind).toBe('standard');

        const blobPath = join(packageStoreDir, REAL_APLUSB_HASH.slice(0, 2), REAL_APLUSB_HASH);
        expect((await stat(blobPath)).isFile()).toBe(true);
      } finally {
        await close();
      }
    },
    120_000,
  );
});
